context:
  version: "2.0.1"
  python_min: "3.10"

package:
  name: fasta2a
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fasta2a/fasta2a-${{ version }}.tar.gz
    sha256: f044485ddb7d8904a58b3de2ae924ff9d227be142f79c489e54c95acc2a660c9

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.28.0
    - pydantic >=2.10
    - starlette >0.29.0
  run_constraints:
    - logfire >=2.3

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - fasta2a
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: Convert an AI Agent into a A2A server! ✨
  documentation: https://pydantic.github.io/fasta2a
  homepage: https://github.com/pydantic/fasta2a
  repository: https://github.com/pydantic/fasta2a

extra:
  recipe-maintainers:
    - moritzwilksch
